using AdventOfCode2025.Days;
using FluentAssertions;
using Xunit;

namespace AdventOfCode2025Tests;

public class Day07Tests
{
    private const string input =
@".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
";

    [Fact]
    public void Day07Part1()
    {
        var output = new Day07().SolvePart1(input);

        output.Should().Be("21");
    }

    [Fact]
    public void Day07Part2()
    {
        var output = new Day07().SolvePart2(input);

        output.Should().Be("40");
    }
}
